aliexpress_affiliate_enabled:
  default: true
  client: false
  type: bool

aliexpress_affiliate_app_key:
  default: "529034"
  client: false
  type: string

aliexpress_affiliate_app_secret:
  default: ""
  client: false
  type: string
  secret: true
  
aliexpress_affiliate_tracking_id:
  default: "default"
  client: false
  type: string